version: '2'
services:
  nginx:
      build:
        context: .
        dockerfile: ./docker-config/nginx/Dockerfile
      ports:
          - 80:80
      volumes:
          - cpresources:/var/www/html/web/cpresources

  php:
      build:
        context: .
        dockerfile: ./docker-config/php/Dockerfile
      expose:
          - 9000
      volumes:
          - cpresources:/var/www/html/web/cpresources
      environment:
        ENVIRONMENT: dev
        DB_DRIVER: mysql
        DB_SERVER: database
        DB_USER: root
        DB_PASSWORD: secret
        DB_DATABASE: pre_flight
        DB_SCHEMA: public
        DB_TABLE_PREFIX: craft_
        SITE_URL: http://localhost
        SECURITY_KEY: AAAAAAAAAAAAAAAAAAAAAAAAAAA
        PP_SANDBOX_ID: ATVGt7AcJz-Ls490o85jIRmxmqTKXtAdeEtEI9oAaUP3Om2LDqh3kMc-7bT7n5RBh6NgqPwDygwShByn
        PP_SANDBOX_SECRET: EBXi16OqruSr95BrwwPolLHoYogT4dWZgrLloSfIvdJT7PcROh5GYEl8-FyUeWOUB3oCIsR2KBmTGxD4
        SUPPORT_EMAIL: minohsuh@gmail.com

  database:
      image: mariadb:10.3
      volumes:
          - db-data:/var/lib/mysql
      ports:
          - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: project
          MYSQL_USER: project
          MYSQL_PASSWORD: project

volumes:
  db-data:
  cpresources:
